version: "3"

services:
  app:
    container_name: mini-trello-fe
    image: mini-trello-fe
    build:
      context: .
      # target: production
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    networks:
      - mini-trello

networks:
  mini-trello:
    name: mini-trello
    external: true
